FileVersion = 1
Projects = {NRI = {Path = "Core/NRI"}, "NRI.Vulkan" = {Path = "Core/NRI.Vulkan"}, Bulkan = {Path = "Dependencies/Bulkan"}, "NRI.Framework" = {Path = "Framework/NRI.Framework"}, SDL2 = "*", "Samples.Triangle" = {Path = "Samples/Samples.Triangle"}, "Samples.Clear" = {Path = "Samples/Samples.Clear"}, "NRI.Framework.SDL" = {Path = "Framework/NRI.Framework.SDL"}, Dxc-Beef = {Path = "Dependencies/Dxc-Beef"}, StbImageBeef = {Path = "Dependencies/StbImageBeef"}, Detex = {Path = "Dependencies/Detex"}, "NRI.D3D12" = {Path = "Core/NRI.D3D12"}, Win32 = {Path = "Dependencies/Win32"}, "NRI.D3DCommon" = {Path = "Core/NRI.D3DCommon"}, "Win32.WinPixEventRuntime" = {Path = "Dependencies/Win32.WinPixEventRuntime"}, "NRI.Validation" = {Path = "Core/NRI.Validation"}}
WorkspaceFolders = {Samples = ["Samples.Triangle", "Samples.Clear"], Dependencies = ["Bulkan", "corlib", "SDL2", "Dxc-Beef", "StbImageBeef", "Detex", "Win32", "Win32.WinPixEventRuntime"], Core = ["NRI", "NRI.Vulkan", "NRI.D3D12", "NRI.D3DCommon", "NRI.Validation"], Framework = ["NRI.Framework", "NRI.Framework.SDL"]}

[Workspace]
StartupProject = "Samples.Triangle"

[Configs.Debug.Win64]
AllocType = "Stomp"
