FileVersion = 1
Projects = {nri = {Path = "Engine/nri"}, "nri.vulkan" = {Path = "Engine/nri.vulkan"}, Bulkan = {Path = "Dependencies/Bulkan"}, "nri.sampleFramework" = {Path = "Samples/nri.sampleFramework"}, SDL2 = "*", "nri.sampleTriangle" = {Path = "Samples/nri.sampleTriangle"}, "nri.sampleClear" = {Path = "Samples/nri.sampleClear"}, "nri.sampleFramework.SDL" = {Path = "Samples/nri.sampleFramework.SDL"}, Dxc-Beef = {Path = "Dependencies/Dxc-Beef"}}
WorkspaceFolders = {Samples = ["nri.sampleFramework", "nri.sampleTriangle", "nri.sampleClear", "nri.sampleFramework.SDL"], Dependencies = ["Bulkan", "corlib", "SDL2", "Dxc-Beef"], Engine = ["nri", "nri.vulkan"]}

[Workspace]
StartupProject = "nri.sampleClear"
