FileVersion = 1
Dependencies = {corlib = "*", "nri.vulkan" = "*", "nri.sampleFramework.SDL" = "*", Dxc-Beef = "*", StbImageBeef = "*"}

[Project]
Name = "nri.sampleTriangle"
StartupObject = "nri.sampleTriangle.Program"
