FileVersion = 1
Dependencies = {corlib = "*", NRI = "*", Detex = "*", StbImageBeef = "*", Dxc-Beef = "*", "NRI.D3D12" = "*", "NRI.Vulkan" = "*", "NRI.Validation" = "*"}

[Project]
Name = "NRI.Framework"
TargetType = "BeefLib"
StartupObject = "NRI.Framework.Program"
